data_root_path_en: "../data/flickr30k"
data_root_path_ro: "../data/coco/output"

language: "ro"

model_saved_path: "../outputs/lstm_dec_2lay11_16_30/ckpts/model-epoch=03.ckpt"

model_name: "ro_lstm_256_512_2_0.3"

encoder:
  name: "resnet18"
  latent_dim: 256

#decoder:
#   name: "lstm"
#   embed_size: 256
#   hidden_size: 512
#   num_layers: 2
#   dropout_prob: 0.3

decoder:
  name: "transformer"
  d_model: 256
  d_ff: 512
  nheads: 4
  num_layers: 2
  dropout_prob: 0.3

lr: 0.001
# lr: 0.001
use_data_augmentation: False
epochs: 15
batch_size: 32